[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "=1.0.65"
serialport = "4.2.0"
thrift = "0.17.0"
thrift-import = { path = "../thrift-import" }

[build-dependencies]
thrift-build = { path = "../thrift-build" }

